// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5GfIQrnj2IEAMKQ5ZvsbDwT9VklN-iKs',
    appId: '1:970306274765:web:93c9066488ac4f2f62f084',
    messagingSenderId: '970306274765',
    projectId: 'aplicacionpdam1',
    authDomain: 'aplicacionpdam1.firebaseapp.com',
    storageBucket: 'aplicacionpdam1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByQP3N2uvXD_WqJ2fJvBAXNgz3wgsxeg4',
    appId: '1:970306274765:android:0703ebb6076a8ee262f084',
    messagingSenderId: '970306274765',
    projectId: 'aplicacionpdam1',
    storageBucket: 'aplicacionpdam1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsdee-MmqmDwL_Kgv0jq2Ji5gcbMHRSpo',
    appId: '1:970306274765:ios:4579116d53ac9d3b62f084',
    messagingSenderId: '970306274765',
    projectId: 'aplicacionpdam1',
    storageBucket: 'aplicacionpdam1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsdee-MmqmDwL_Kgv0jq2Ji5gcbMHRSpo',
    appId: '1:970306274765:ios:058c9674a5f6441562f084',
    messagingSenderId: '970306274765',
    projectId: 'aplicacionpdam1',
    storageBucket: 'aplicacionpdam1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
